# Copyright 2018 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: batch/v1
kind: Job
metadata:
  name: resnet-gpu
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: resnet-gpu
        image: gcr.io/k8s-image-staging/tf-models-gpu:1.0
        command:
          - python
          - /tensorflow_models/models/official/resnet/resnet_main.py
          - --use_tpu=False
          - --tpu=
          - --precision=float32
          - --data_dir=gs://cloud-tpu-test-datasets/fake_imagenet
          - --model_dir=gs://<my-bucket>/resnet/model
          - --train_batch_size=<train_batch_size>
          - --train_steps=<train_steps>
        resources:
          limits:
            nvidia.com/gpu: 1
